/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DailyTodoPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
function getVaultFolderPaths(app) {
  const folders = [];
  const visit = (folder) => {
    if (folder.path) {
      folders.push(folder.path);
    }
    for (const child of folder.children) {
      if (child instanceof import_obsidian.TFolder) {
        visit(child);
      }
    }
  };
  visit(app.vault.getRoot());
  return folders.sort((a, b) => a.localeCompare(b));
}
var DEFAULT_SETTINGS = {
  todoFolder: "",
  fileNameSuffix: "TODO",
  todoTag: "todo",
  includeHeading: true,
  setupComplete: false
};
var DailyTodoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const folderPaths = getVaultFolderPaths(this.app);
    const currentFolder = this.plugin.settings.todoFolder.trim();
    if (currentFolder && !folderPaths.includes(currentFolder)) {
      folderPaths.unshift(currentFolder);
    }
    new import_obsidian.Setting(containerEl).setName("TODO folder").setDesc("Vault folder where daily TODO notes are stored.").addDropdown((dropdown) => {
      if (!currentFolder) {
        dropdown.addOption("", "Not configured \u2014 use the ribbon icon to set up");
      }
      if (folderPaths.length === 0 && !currentFolder) {
        dropdown.addOption("TODO", "TODO (will be created)");
      } else {
        for (const path of folderPaths) {
          dropdown.addOption(path, path || "/");
        }
      }
      dropdown.setValue(currentFolder || "").onChange(async (value) => {
        this.plugin.settings.todoFolder = value;
        this.plugin.settings.setupComplete = true;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("File name suffix").setDesc('Optional suffix after the date (e.g. "TODO" produces "2025-06-09 TODO.md"). A space is added automatically. Leave blank for "YYYY-MM-DD.md".').addText(
      (text) => text.setPlaceholder("TODO").setValue(this.plugin.settings.fileNameSuffix).onChange(async (value) => {
        this.plugin.settings.fileNameSuffix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("TODO tag").setDesc("Tag added to the frontmatter of new daily TODO notes.").addText(
      (text) => text.setPlaceholder("todo").setValue(this.plugin.settings.todoTag).onChange(async (value) => {
        this.plugin.settings.todoTag = value.trim() || DEFAULT_SETTINGS.todoTag;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Include heading").setDesc("Add a '# TODO' heading below the frontmatter in new notes.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeHeading).onChange(async (value) => {
        this.plugin.settings.includeHeading = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// first-run-setup.ts
var import_obsidian3 = require("obsidian");

// todo-rollover.ts
var import_obsidian2 = require("obsidian");
var DATE_PATTERN = /^(\d{4})-(\d{2})-(\d{2})/;
var UNCHECKED_TASK_PATTERN = /^\s*[-*+]\s+\[\s\]\s+/;
var CHECKED_TASK_PATTERN = /^\s*[-*+]\s+\[[xX]\]\s+/;
var LIST_ITEM_PATTERN = /^\s*(?:[-*+]\s+(?:\[[\sxX]\]\s+)?|\d+\.\s+)/;
var FRONTMATTER_PATTERN = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/;
var TODO_HEADING_PATTERN = /^#\s+TODO\s*$/i;
var NOTES_HEADING_PATTERN = /^##\s+Notes\s*$/i;
function getIndent(line) {
  const match = line.match(/^(\s*)/);
  return match ? match[1].replace(/\t/g, "    ").length : 0;
}
function isBlockListItem(line) {
  return LIST_ITEM_PATTERN.test(line);
}
function findNextNonEmptyLine(lines, start) {
  for (let i = start; i < lines.length; i++) {
    if (lines[i].trim() !== "") {
      return i;
    }
  }
  return -1;
}
function formatDate(date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
function sanitizeFolderPath(folder) {
  const trimmed = folder.trim().replace(/\\/g, "/");
  if (!trimmed) {
    return "TODO";
  }
  const normalized = (0, import_obsidian2.normalizePath)(trimmed);
  if (!normalized || normalized === "." || normalized === ".." || normalized.includes("..")) {
    return "TODO";
  }
  return normalized;
}
function parseDateFromBasename(basename) {
  const match = basename.match(DATE_PATTERN);
  if (!match) {
    return null;
  }
  const [, year, month, day] = match;
  const monthNum = Number(month);
  const dayNum = Number(day);
  const yearNum = Number(year);
  if (monthNum < 1 || monthNum > 12 || dayNum < 1 || dayNum > 31) {
    return null;
  }
  const parsed = new Date(yearNum, monthNum - 1, dayNum);
  if (parsed.getFullYear() !== yearNum || parsed.getMonth() !== monthNum - 1 || parsed.getDate() !== dayNum) {
    return null;
  }
  return `${year}-${month}-${day}`;
}
function buildFileName(date, suffix) {
  const safeSuffix = suffix.replace(/[<>:"/\\|?*]/g, "").trim();
  return safeSuffix ? `${date} ${safeSuffix}.md` : `${date}.md`;
}
function buildLegacyFileName(date, suffix) {
  const safeSuffix = suffix.replace(/[<>:"/\\|?*]/g, "").trim();
  return safeSuffix ? `${date}${safeSuffix}.md` : `${date}.md`;
}
function stripFrontmatter(content) {
  return content.replace(FRONTMATTER_PATTERN, "");
}
function extractTodoSectionLines(content) {
  const lines = stripFrontmatter(content).split(/\r?\n/);
  let start = 0;
  let end = lines.length;
  for (let i = 0; i < lines.length; i++) {
    if (TODO_HEADING_PATTERN.test(lines[i].trim())) {
      start = i + 1;
      while (start < lines.length && lines[start].trim() === "") {
        start++;
      }
      break;
    }
  }
  for (let i = start; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (NOTES_HEADING_PATTERN.test(trimmed)) {
      end = i;
      break;
    }
    if (/^#\s+/.test(trimmed) && !TODO_HEADING_PATTERN.test(trimmed)) {
      end = i;
      break;
    }
  }
  return lines.slice(start, end);
}
function skipSubtree(lines, start, blockIndent) {
  let j = start + 1;
  while (j < lines.length) {
    const line = lines[j];
    if (line.trim() === "") {
      const nextIdx = findNextNonEmptyLine(lines, j + 1);
      if (nextIdx === -1 || getIndent(lines[nextIdx]) > blockIndent) {
        j++;
        continue;
      }
      break;
    }
    if (getIndent(line) <= blockIndent) {
      break;
    }
    j++;
  }
  return j;
}
function collectNestedLines(lines, start, parentIndent) {
  const result = [];
  let j = start;
  while (j < lines.length) {
    const line = lines[j];
    if (line.trim() === "") {
      const nextIdx = findNextNonEmptyLine(lines, j + 1);
      if (nextIdx === -1 || getIndent(lines[nextIdx]) > parentIndent) {
        result.push(line);
        j++;
        continue;
      }
      break;
    }
    const indent = getIndent(line);
    if (indent <= parentIndent) {
      if (isBlockListItem(line)) {
        break;
      }
      break;
    }
    if (CHECKED_TASK_PATTERN.test(line)) {
      j = skipSubtree(lines, j, indent);
      continue;
    }
    if (UNCHECKED_TASK_PATTERN.test(line)) {
      result.push(line);
      const nested = collectNestedLines(lines, j + 1, indent);
      result.push(...nested.lines);
      j = nested.end;
      continue;
    }
    result.push(line);
    j++;
  }
  return { lines: result, end: j };
}
function collectIncompleteTodoBlocks(content) {
  const lines = extractTodoSectionLines(content);
  const incomplete = [];
  let todoCount = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!UNCHECKED_TASK_PATTERN.test(line)) {
      continue;
    }
    todoCount++;
    incomplete.push(line);
    const nested = collectNestedLines(lines, i + 1, getIndent(line));
    incomplete.push(...nested.lines);
    i = nested.end - 1;
  }
  return { lines: incomplete, todoCount };
}
function findTodoFilesInFolder(app, folderPath) {
  const folder = app.vault.getAbstractFileByPath(folderPath);
  if (!folder) {
    return [];
  }
  const files = [];
  const visit = (path) => {
    const folderEntry = app.vault.getAbstractFileByPath(path);
    if (!folderEntry || !(folderEntry instanceof import_obsidian2.TFolder)) {
      return;
    }
    for (const child of folderEntry.children) {
      if (child instanceof import_obsidian2.TFile && child.extension === "md") {
        if (parseDateFromBasename(child.basename)) {
          files.push(child);
        }
      } else if (child instanceof import_obsidian2.TFolder) {
        visit(child.path);
      }
    }
  };
  visit(folderPath);
  return files;
}
function findMostRecentTodoFile(app, folderPath, beforeDate) {
  var _a, _b;
  const files = findTodoFilesInFolder(app, folderPath);
  if (files.length === 0) {
    return null;
  }
  const datedFiles = files.map((file) => ({
    file,
    date: parseDateFromBasename(file.basename)
  })).filter((entry) => entry.date !== null);
  if (beforeDate) {
    const filtered = datedFiles.filter((entry) => entry.date < beforeDate);
    if (filtered.length === 0) {
      return null;
    }
    filtered.sort((a, b) => b.date.localeCompare(a.date));
    return filtered[0].file;
  }
  datedFiles.sort((a, b) => b.date.localeCompare(a.date));
  return (_b = (_a = datedFiles[0]) == null ? void 0 : _a.file) != null ? _b : null;
}
function buildNoteContent(settings, today, sourceBasename, incompleteLines) {
  const tags = ["daily", settings.todoTag].filter(Boolean);
  const uniqueTags = [...new Set(tags)];
  const frontmatterLines = [
    "---",
    `tags: [${uniqueTags.map((tag) => tag).join(", ")}]`,
    `date: ${today}`,
    "type: daily-todo"
  ];
  if (sourceBasename) {
    frontmatterLines.push(`rolledOverFrom: "[[${sourceBasename}]]"`);
  }
  frontmatterLines.push("---", "");
  const bodyLines = [];
  if (settings.includeHeading) {
    bodyLines.push("# TODO", "");
  }
  if (incompleteLines.length > 0) {
    bodyLines.push(...incompleteLines);
  } else {
    bodyLines.push("- [ ] ");
  }
  bodyLines.push("");
  bodyLines.push(settings.includeHeading ? "## Notes" : "# Notes", "");
  return [...frontmatterLines, ...bodyLines].join("\n");
}
async function ensureFolderExists(app, folderPath) {
  const existing = app.vault.getAbstractFileByPath(folderPath);
  if (existing) {
    return;
  }
  const parts = folderPath.split("/").filter(Boolean);
  let current = "";
  for (const part of parts) {
    current = current ? `${current}/${part}` : part;
    if (!app.vault.getAbstractFileByPath(current)) {
      await app.vault.createFolder(current);
    }
  }
}
async function rolloverTodos(app, settings) {
  const folderPath = sanitizeFolderPath(settings.todoFolder);
  const today = formatDate(new Date());
  const todayFileName = buildFileName(today, settings.fileNameSuffix);
  const todayFilePath = (0, import_obsidian2.normalizePath)(`${folderPath}/${todayFileName}`);
  let existingToday = app.vault.getAbstractFileByPath(todayFilePath);
  if (!(existingToday instanceof import_obsidian2.TFile)) {
    const legacyFileName = buildLegacyFileName(today, settings.fileNameSuffix);
    if (legacyFileName !== todayFileName) {
      const legacyFilePath = (0, import_obsidian2.normalizePath)(`${folderPath}/${legacyFileName}`);
      const legacyFile = app.vault.getAbstractFileByPath(legacyFilePath);
      if (legacyFile instanceof import_obsidian2.TFile) {
        await app.vault.rename(legacyFile, todayFilePath);
        existingToday = app.vault.getAbstractFileByPath(todayFilePath);
      }
    }
  }
  if (existingToday instanceof import_obsidian2.TFile) {
    new import_obsidian2.Notice(`Today's TODO already exists: ${todayFileName}`);
    await app.workspace.getLeaf(false).openFile(existingToday);
    return {
      created: false,
      file: existingToday,
      sourceDate: null,
      itemCount: 0
    };
  }
  const sourceFile = findMostRecentTodoFile(app, folderPath, today);
  let incompleteLines = [];
  let sourceDate = null;
  let sourceBasename = null;
  let todoCount = 0;
  if (sourceFile) {
    sourceBasename = sourceFile.basename;
    sourceDate = parseDateFromBasename(sourceFile.basename);
    const sourceContent = await app.vault.read(sourceFile);
    const blocks = collectIncompleteTodoBlocks(sourceContent);
    incompleteLines = blocks.lines;
    todoCount = blocks.todoCount;
  }
  await ensureFolderExists(app, folderPath);
  const content = buildNoteContent(settings, today, sourceBasename, incompleteLines);
  const newFile = await app.vault.create(todayFilePath, content);
  await app.workspace.getLeaf(false).openFile(newFile);
  const itemLabel = todoCount === 1 ? "item" : "items";
  const sourceLabel = sourceDate ? ` from ${sourceDate}` : "";
  new import_obsidian2.Notice(
    `Created ${todayFileName} with ${todoCount} rolled-over ${itemLabel}${sourceLabel}.`
  );
  return {
    created: true,
    file: newFile,
    sourceDate,
    itemCount: todoCount
  };
}

// first-run-setup.ts
var DEFAULT_SETUP_FOLDER = "_TODO";
function todoFolderExists(app, folderPath) {
  const trimmed = folderPath.trim();
  if (!trimmed) {
    return false;
  }
  const entry = app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(trimmed));
  return entry instanceof import_obsidian3.TFolder;
}
function needsFirstRunSetup(app, settings) {
  if (!settings.setupComplete) {
    return true;
  }
  if (!settings.todoFolder.trim()) {
    return true;
  }
  return !todoFolderExists(app, settings.todoFolder);
}
async function markSetupComplete(plugin) {
  plugin.settings.setupComplete = true;
  await plugin.saveSettings();
}
function buildExampleYesterdayContent(settings, date) {
  const tags = ["daily", settings.todoTag].filter(Boolean);
  const uniqueTags = [...new Set(tags)];
  const frontmatterLines = [
    "---",
    `tags: [${uniqueTags.join(", ")}]`,
    `date: ${date}`,
    "type: daily-todo",
    "---",
    ""
  ];
  const bodyLines = [];
  if (settings.includeHeading) {
    bodyLines.push("# TODO", "");
  }
  bodyLines.push(
    "- [ ] Connect todo folder",
    "	- [ ] check the rolled over link in page properties",
    "	- [ ] speed up daily todo creation",
    "- [ ] Follow up with team",
    "	- [x] Draft email to George P. Burdell",
    "	- [ ] Review standup notes",
    "- [ ] Try the Daily TODO rollover",
    "	- [ ] Have fun!"
  );
  bodyLines.push("");
  bodyLines.push(settings.includeHeading ? "## Notes" : "# Notes", "");
  bodyLines.push("Example note from first-run setup. Incomplete items above will roll over.");
  return [...frontmatterLines, ...bodyLines].join("\n");
}
async function setupDefaultTodoFolder(plugin) {
  const folderPath = DEFAULT_SETUP_FOLDER;
  await ensureFolderExists(plugin.app, folderPath);
  plugin.settings.todoFolder = folderPath;
  await markSetupComplete(plugin);
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);
  const yesterdayStr = formatDate(yesterday);
  const fileName = buildFileName(yesterdayStr, plugin.settings.fileNameSuffix);
  const filePath = (0, import_obsidian3.normalizePath)(`${folderPath}/${fileName}`);
  if (!plugin.app.vault.getAbstractFileByPath(filePath)) {
    const content = buildExampleYesterdayContent(plugin.settings, yesterdayStr);
    await plugin.app.vault.create(filePath, content);
  }
}
var TodoFolderSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, folders, onChooseFolder, onCancel) {
    super(app);
    this.chosen = false;
    this.folders = folders;
    this.onChooseFolder = onChooseFolder;
    this.onCancel = onCancel;
  }
  getItems() {
    return this.folders;
  }
  getItemText(item) {
    return item || "/ (vault root)";
  }
  onChooseItem(item) {
    this.chosen = true;
    this.onChooseFolder(item);
  }
  onClose() {
    super.onClose();
    if (!this.chosen) {
      this.onCancel();
    }
  }
};
var FirstRunSetupModal = class extends import_obsidian3.Modal {
  constructor(app, handlers, onCloseWithoutAction) {
    super(app);
    this.closingForAction = false;
    this.handlers = handlers;
    this.onCloseWithoutAction = onCloseWithoutAction;
  }
  onOpen() {
    const { contentEl, titleEl } = this;
    contentEl.empty();
    titleEl.setText("Set up Daily TODO");
    contentEl.createEl("p", {
      text: "Before creating today's list, choose where your daily TODO notes should live."
    });
    new import_obsidian3.Setting(contentEl).setName("Browse folders").setDesc("Pick an existing folder in your vault for daily TODO notes.").addButton(
      (button) => button.setButtonText("Browse folders").setCta().onClick(() => {
        const folders = getVaultFolderPaths(this.app);
        if (folders.length === 0) {
          new import_obsidian3.Notice("No folders found in your vault. Try creating _TODO instead.");
          return;
        }
        this.closingForAction = true;
        this.close();
        new TodoFolderSuggestModal(
          this.app,
          folders,
          (folder) => this.handlers.onBrowseFolder(folder),
          () => this.handlers.onDismiss()
        ).open();
      })
    );
    new import_obsidian3.Setting(contentEl).setName(`Create ${DEFAULT_SETUP_FOLDER}`).setDesc(
      `Create a ${DEFAULT_SETUP_FOLDER} folder with a sample yesterday note so you can test rollover right away.`
    ).addButton(
      (button) => button.setButtonText(`Create ${DEFAULT_SETUP_FOLDER}`).setCta().onClick(() => {
        this.closingForAction = true;
        this.close();
        this.handlers.onCreateDefault();
      })
    );
    new import_obsidian3.Setting(contentEl).addButton(
      (button) => button.setButtonText("Cancel").onClick(() => this.close())
    );
  }
  onClose() {
    this.contentEl.empty();
    if (!this.closingForAction) {
      this.onCloseWithoutAction();
    }
  }
};
function showFirstRunSetup(plugin) {
  return new Promise((resolve) => {
    let finished = false;
    const finish = () => {
      if (!finished) {
        finished = true;
        resolve();
      }
    };
    const runRollover = async () => {
      try {
        await rolloverTodos(plugin.app, plugin.settings);
      } catch (error) {
        console.error("Daily TODO rollover failed after setup:", error);
        new import_obsidian3.Notice(
          "Setup saved, but creating today's TODO failed. Check the developer console for details."
        );
      } finally {
        finish();
      }
    };
    new FirstRunSetupModal(
      plugin.app,
      {
        onBrowseFolder: (folder) => {
          void (async () => {
            plugin.settings.todoFolder = folder;
            await markSetupComplete(plugin);
            await runRollover();
          })();
        },
        onCreateDefault: () => {
          void (async () => {
            await setupDefaultTodoFolder(plugin);
            await runRollover();
          })();
        },
        onDismiss: finish
      },
      finish
    ).open();
  });
}

// main.ts
var DailyTodoPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("list-checks", "Create today's TODO", () => {
      void this.createTodaysTodo();
    });
    this.addCommand({
      id: "create-todays-todo",
      name: "Create today's TODO from previous day",
      callback: () => {
        void this.createTodaysTodo();
      }
    });
    this.addSettingTab(new DailyTodoSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = { ...DEFAULT_SETTINGS, ...saved };
    if (this.settings.setupComplete === void 0) {
      this.settings.setupComplete = saved != null && typeof saved === "object" && Object.keys(saved).length > 0;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async createTodaysTodo() {
    try {
      if (needsFirstRunSetup(this.app, this.settings)) {
        await showFirstRunSetup(this);
        return;
      }
      await rolloverTodos(this.app, this.settings);
    } catch (error) {
      console.error("Daily TODO rollover failed:", error);
      new import_obsidian4.Notice("Failed to create today's TODO. Check the developer console for details.");
    }
  }
};
